name: dataportal
channels:
  - conda-forge
dependencies:
  - python=3.7
  - iris=2.3
  - jupyter
  - jupyterlab
  - jinja2
  - pandoc
  - intake
  - papermill
  - geoviews
  - voila
  - dash
  - panel
